version: '3'
services:
  controller:
    image: locustio/locust
    ports:
      - '8089:8089'
    volumes:
      - ./:/mnt/locust
    command: --config /mnt/locust/steeltoe-staging.conf --locustfile /mnt/locust/locustfile.py --master
  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: --config /mnt/locust/steeltoe-staging.conf --locustfile /mnt/locust/locustfile.py --worker --master-host controller
